# git push origin main
# YandexCloud creat VM Ubuntu 2CPU 2RAM 300Gb User:essch SSH:essch Name:ml2
# ssh -l essch 158.160.61.241
# git clone https://github.com/ESSch/ML.git
# sudo apt-get update
# sudo apt-get install docker.io
# docker -v
# cd ML
# git pull origin main
# cat dockerfile_db
# sudo docker build -t db -f dockerfile_db .
# docker run -p 8000:8000 db
FROM python:3

WORKDIR /app
COPY . .
RUN pip install --upgrade pip
RUN pip install sentence-transformers 
RUN pip install chromadb